enemy_IDs = {
    24: "Snowbot",
    25: "Wolf",
    26: "Snowtank",
    27: "Lil Hunter",
    21: "Laser Crystal",
    22: "Hyper Crystal",
    23: "Snow Bandit",
    28: "Freak",
    29: "Explo Freak",
    0: "Bandit",
    4: "Scorpion",
    8: "Rat King",
    59: "Toxin",
    58: "Shield",
    55: "Explosion",
    54: "Crown Guardian",
    57: "Fire Trap",
    56: "Small Explosion",
    51: "Grunt",
    50: "Health Mimic",
    53: "Shielder",
    52: "Inspector",
    -1: "Nothing",
    88: "Underwater Lightning",
    89: "Elite Grunt",
    82: "Jungle Bandit",
    83: "Jungle Assassin",
    80: "Lil Hunter Fly",
    81: "Throne Death",
    86: "Ice Flower",
    87: "Cursed Ammo Pickup",
    84: "Jungle Fly",
    85: "Crown of Hatred",
    3: "Big Maggot",
    7: "Rat",
    102: "Big Dog Explosion",
    103: "IDPD Freak",
    100: "Small Generator",
    101: "Golden Disc",
    104: "Throne II Death",
    39: "Bone Fish",
    38: "Throne II",
    33: "Technomancer",
    32: "Turret",
    31: "Necromancer",
    30: "Rhino Freak",
    37: "Throne",
    36: "Dog Guardian",
    35: "Explo Guardian",
    34: "Guardian",
    60: "Horror",
    61: "Barrel",
    62: "Toxic Barrel",
    63: "Golden Barrel",
    64: "Car",
    65: "Venus Car",
    66: "Venus Car Fixed",
    67: "Venus Car 2",
    68: "Icy Car",
    69: "Thrown Car",
    2: "Rad Maggot",
    6: "Big Bandit",
    99: "Green Explosion",
    98: "Golden Snowtank",
    91: "Elite Shielder",
    90: "Blood Gamble",
    93: "Captain",
    92: "Elite Inspector",
    95: "Buff Gator",
    94: "Van",
    97: "Lightning Crystal",
    96: "Generator",
    11: "Exploder",
    10: "Gator",
    13: "Mom",
    12: "Toxic Frog",
    15: "Raven",
    14: "Assassin",
    17: "Sniper",
    16: "Salamander",
    19: "Spider",
    18: "Big Dog",
    48: "Cursed Crystal",
    49: "Mimic",
    46: "Jock",
    47: "Cursed Spider",
    44: "Fire Baller",
    45: "Super Fireballer",
    42: "Venus Grunt",
    43: "Venus Sarge",
    40: "Crab",
    41: "Turtle",
    1: "Maggot",
    5: "Gold Scorpion",
    9: "Green Rat",
    77: "Curse Eat",
    76: "Disc",
    75: "Blood Hammer",
    74: "Blood Cannon",
    73: "Blood Launcher",
    72: "Rogue Strike",
    71: "Crown of Death",
    70: "Mine",
    79: "Halloween Bandit",
    78: "Big Dog Missle"
}



weapon_IDs = {
    24: "Energy Sword",
    25: "Super Slugger",
    26: "Hyper Rifle",
    27: "Screwdriver",
    20: "Laser Rifle",
    21: "Slugger",
    22: "Gatling Slugger",
    23: "Assault Slugger",
    28: "Laser Minigun",
    29: "Blood Launcher",
    0: "Nothing",
    4: "Machinegun",
    8: "Double Shotgun",
    119: "Super Bazooka",
    120: "Frog Pistol",
    121: "Black Sword",
    122: "Golden Nuke Launcher",
    123: "Golden Disc Gun",
    124: "Heavy Grenade Launcher",
    125: "Gun Gun",
    201: "Golden Frog Pistol",
    118: "Hyper Slugger",
    59: "Lightning Shotgun",
    58: "Lightning Rifle",
    55: "Laser Cannon",
    54: "Hyper Launcher",
    57: "Lightning Pistol",
    56: "Rusty Revolver",
    51: "Dragon",
    50: "Flamethrower",
    53: "Energy Screwdriver",
    52: "Flare Gun",
    115: "Guitar",
    114: "Eraser",
    88: "Sledgehammer",
    89: "Heavy Revolver",
    111: "Super Plasma Cannon",
    110: "Incinerator",
    113: "Seeker Shotgun",
    112: "Seeker Pistol",
    82: "Party Gun",
    83: "Double Minigun",
    80: "Grenade Rifle",
    81: "Rogue Rifle",
    86: "Ultra Revolver",
    87: "Ultra Laser Pistol",
    84: "Gatling Bazooka",
    85: "Auto Grenade Shotgun",
    3: "Wrench",
    7: "Grenade Launcher",
    108: "Dog Spin Attack",
    109: "Dog Missle",
    102: "Golden Bazooka",
    103: "Golden Assault Rifle",
    100: "Golden Splinter Gun",
    101: "Golden Screwdriver",
    106: "Heavy Assault Rifle",
    107: "Blood Cannon",
    104: "Super Disc Gun",
    105: "Heavy Auto Crossbow",
    39: "Golden Revolver",
    38: "Energy Hammer",
    33: "Wave Gun",
    32: "Sentry Gun",
    31: "Toxic Bow",
    30: "Splinter Gun",
    37: "Jackhammer",
    36: "Energy Hammer",
    35: "Plasma Cannon",
    34: "Plasma Gun",
    60: "Super Flak Cannon",
    61: "Sawed-Off Shotgun",
    62: "Splinter Pistol",
    63: "Super Splinter Pistol",
    64: "Lightning SMG",
    65: "Smart Gun",
    66: "Heavy Crossbow",
    67: "Blood Hammer",
    68: "Lightning Cannon",
    69: "Pop Gun",
    2: "Triple Machinegun",
    6: "Crossbow",
    99: "Golden Slugger",
    98: "Golden Plasma Gun",
    91: "Heavy Slugger",
    90: "Heavy Machinegun",
    93: "Ultra Shotgun",
    92: "Ultra Shovel",
    95: "Ultra Grenade Launcher",
    94: "Ultra Crossbow",
    97: "Devastator",
    96: "Plasma Minigun",
    11: "Auto Crossbow",
    10: "Auto Shotgun",
    13: "Shovel",
    12: "Super Crossbow",
    15: "Sticky Launcher",
    14: "Bazooka",
    17: "Assault Rifle",
    16: "SMG",
    19: "Laser Pistol",
    18: "Disc Gun",
    117: "Bouncer Shotgun",
    116: "Bouncer SMG",
    48: "Ion Cannon",
    49: "Quadruple Machinegun",
    46: "Chicken Sword",
    47: "Nuke Launcher",
    44: "Golden Grenade Launcher",
    45: "Golden Laser Pistol",
    42: "Golden Shotgun",
    43: "Golden Crossbow",
    40: "Golden Wrench",
    41: "Golden Machinegun",
    1: "Revolver",
    5: "Shotgun",
    9: "Minigun",
    77: "Auto Flame Shotgun",
    76: "Double Flame Shotgun",
    75: "Flame Shotgun",
    74: "Lightning Hammer",
    73: "Flame Cannon",
    72: "Toxic Launcher",
    71: "Pop Rifle",
    70: "Plasma Rifle",
    79: "Grenade Shotgun",
    78: "Cluster Launcher"
}



character_IDs = {
    1: "Fish",
    2: "Crystal",
    3: "Eyes",
    4: "Melting",
    5: "Plant",
    6: "Y.V.",
    7: "Steroids",
    8: "Robot",
    9: "Chicken",
    10: "Rebel",
    11: "Horror",
    12: "Rogue",
    14: "Skeleton",
    15: "Frog"
}


mutation_IDs = {
    0: "Heavy Heart",
    1: "Rhino Skin",
    2: "Extra Feet",
    3: "Plutonium Hunger",
    4: "Rabbit Paw",
    5: "Throne Butt",
    6: "Lucky Shot",
    7: "Bloodlust",
    8: "Gamma Guts",
    9: "Second Stomach",
    10: "Back Muscle",
    11: "Scarier Face",
    12: "Euphoria",
    13: "Long Arms",
    14: "Boiling Veins",
    15: "Shotgun Shoulders",
    16: "Recycle Gland",
    17: "Laser Brain",
    18: "Last Wish",
    19: "Eagle Eyes",
    20: "Impact Wrists",
    21: "Bolt Marrow",
    22: "Stress",
    23: "Trigger Fingers",
    24: "Sharp Teeth",
    25: "Patience",
    26: "Hammerhead",
    27: "Strong Spirit",
    28: "Open Mind"
}



crown_IDs = {
    1: "No Crown",
    2: "Crown of Death",
    3: "Crown of Life",
    4: "Crown of Haste",
    5: "Crown of Guns",
    6: "Crown of Hatred",
    7: "Crown of Blood",
    8: "Crown of Destiny",
    9: "Crown of Love",
    10: "Crown of Risk",
    11: "Crown of Curses",
    12: "Crown of Luck",
    13: "Crown of Protection",
}



world_IDs = {
    100: "Crown Vault",
    1: "Desert",
    101: "Oasis",
    2: "Sewers",
    102: "Pizza Sewers",
    3: "Scrapyard",
    103: "Y.V.'s Mansion",
    4: "Crystal Caves",
    104: "Cursed Crystal Caves",
    5: "Frozen City",
    105: "Jungle",
    6: "Labs",
    7: "The Palace",
    0: "Campfire",
    106: "Y.V.'s Crib",
    107: "I.D.P.D. Headquarters",
}